### ISSUE TITLE
Unable to use automatic1111 after problem in this extension. Problem not exclusive to exceptions

### ISSUE THREAD

**Issue by mcDandy** [ArtVentureX/sd-webui-agent-scheduler#200]
Images cannot be generated, GUI does not react to Script selection and PNG info after a problem. Removing extension fixes it

Exception in thread Thread-35 (execute_task):████████████████▏                       | 402/640 [04:35<09:15,  2.34s/it]
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\Users\danda\Downloads\sdwebui\webui\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 352, in execute_task
    res = self.__execute_task(task_id, is_img2img, task_args)
  File "D:\Users\danda\Downloads\sdwebui\webui\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 443, in __execute_task
    return self.__execute_ui_task(task_id, is_img2img, *ui_args)
  File "D:\Users\danda\Downloads\sdwebui\webui\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 473, in __execute_ui_task
    shared.state.end()
  File "D:\Users\danda\Downloads\sdwebui\webui\modules\shared_state.py", line 128, in end
    devices.torch_gc()
  File "D:\Users\danda\Downloads\sdwebui\webui\modules\devices.py", line 61, in torch_gc
    torch.cuda.empty_cache()
  File "D:\Users\danda\Downloads\sdwebui\system\python\lib\site-packages\torch\cuda\memory.py", line 133, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception in thread Thread-52 (execute_task):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\Users\danda\Downloads\sdwebui\webui\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 352, in execute_task
    res = self.__execute_task(task_id, is_img2img, task_args)
  File "D:\Users\danda\Downloads\sdwebui\webui\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 443, in __execute_task
    return self.__execute_ui_task(task_id, is_img2img, *ui_args)
  File "D:\Users\danda\Downloads\sdwebui\webui\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 456, in __execute_ui_task
    shared.state.begin()
  File "D:\Users\danda\Downloads\sdwebui\webui\modules\shared_state.py", line 119, in begin
    devices.torch_gc()
  File "D:\Users\danda\Downloads\sdwebui\webui\modules\devices.py", line 61, in torch_gc
    torch.cuda.empty_cache()
  File "D:\Users\danda\Downloads\sdwebui\system\python\lib\site-packages\torch\cuda\memory.py", line 133, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by Rakna123** [comment]
Did you found the solution. I never updated but 20hrs before my application stopped working due to same error. I changed the server still getting this error.

**Comment by mcDandy** [comment]
It can be temporalry fixed by removing the plugin, running a1111, And
giving thé plugin back (moving the folder from extensions foder)

Dne st 3. 1. 2024 23:09 uživatel Rakna123 ***@***.***> napsal:

**Comment by Rakna123** [comment]
If i restart the server it work and after few minutes getting the same error.
Is moving the plugin from folder solved the problem ?

**Comment by mcDandy** [comment]
It fixes the problém. You will however not be able to use the plugin when
it is out of extensions folder. Moving it back will enable the use of the
extensions (UI should be usable).

Dne st 3. 1. 2024 23:20 uživatel Rakna123 ***@***.***> napsal:

**Comment by Rakna123** [comment]
i done but again error occurs in few minutes. My Application in production so i am restarting every 20 min. 
Is there any permanent solution?

**Comment by mcDandy** [comment]
Did not find any, sadly...

Dne čt 4. 1. 2024 8:16 uživatel Rakna123 ***@***.***> napsal:
